INVALID_EMAIL = "Enter a valid email address."
EMPTY_EMAIL_ID = "Email is required."
EMPTY_PASSWORD = "Password is required."
INCORRECT_CREDENTIALS = "Invalid credentials Please try again with valid credentials ⚠"
CORRECT_CREDENTIALS = "Logged in successfully."
LOGOUT = "Logged out successfully."
INACTIVE = "Community Type has been updated successfully to Inactive."
ACTIVE = "Community Type has been updated successfully to Active."
LANGUAGE = "Language is required."
EMPTY_COMMUNITY_TYPE_NAME = "Name is required."
SPACE_COMMUNITY_TYPE_NAME = "Empty space is not allowed."
CHARACTERS_COMMUNITY_TYPE_NAME = "Special characters are not allowed."
MAX_LENGTH = "Maximum characters allowed is 30."
UNSUPPORTED_FILE = "Unsupported file format. Supported formats are .jpg, .jpeg and .png."
FILE_LIMIT = "Upload image cannot be more than 10 MB!"
QUESTION_INACTIVE = "Question has been updated successfully to Inactive."
QUESTION_ACTIVE = "Question has been updated successfully to Active."
QUESTION_UPDATE = "Question has been updated successfully."
GAME_TRANSLATION = "Translation has been added successfully."
QUESTION_REQUIRED = "Question is required."
EMPTY_SPACE_QUESTION = "Empty space is not allowed."
QUESTION_MAX_LENGTH = "Maximum characters allowed is 100."
EXISTING_QUESTION = "Question Already Exists ⚠"
NEW_QUESTION = "Question has been added successfully."
GAME_EMPTY_LANGUAGE = "Language is required."


